export const RAW_FOODS = [
    { name: "Heart Of Palm", carbs:4, protein:2, fat:0, vitamins:2, cal:100, tier:"gatherer", biomes:["rainforest","forest"] },
    { name: "Bolete Mushrooms", carbs:2, protein:4, fat:1, vitamins:1, cal:200, tier:"gatherer", biomes:["forest"] },
    { name: "Leavened Dough", carbs:6, protein:18, fat:13, vitamins:5, cal:10, tier:"advanced", biomes:["any"] },
    { name: "Charred Taro", carbs:10, protein:1, fat:0, vitamins:1, cal:350, tier:"campfire", biomes:["rainforest","forest"] },
    { name: "Taro Root", carbs:6, protein:1, fat:0, vitamins:1, cal:250, tier:"gatherer", biomes:["rainforest","forest"] },
    { name: "Baked Agave", carbs:14, protein:2, fat:4, vitamins:8, cal:700, tier:"baked", biomes:["desert"] },
    { name: "Huckleberries", carbs:2, protein:0, fat:0, vitamins:6, cal:150, tier:"gatherer", biomes:["forest"] },
    { name: "Pupusas", carbs:6, protein:11, fat:9, vitamins:14, cal:900, tier:"advanced", biomes:["any"] },
    { name: "Vegetable Medley", carbs:8, protein:4, fat:7, vitamins:17, cal:900, tier:"cooked", biomes:["any"] },
    { name: "Huckleberry Fritter", carbs:16, protein:0, fat:20, vitamins:8, cal:900, tier:"baked", biomes:["forest"] },
    { name: "Baked Heart Of Palm", carbs:12, protein:6, fat:4, vitamins:6, cal:700, tier:"baked", biomes:["rainforest"] },
    { name: "Camas Bulb Bake", carbs:12, protein:7, fat:5, vitamins:4, cal:700, tier:"baked", biomes:["grassland"] },
    { name: "Pineapple", carbs:6, protein:0, fat:0, vitamins:2, cal:200, tier:"gatherer", biomes:["rainforest"] },
    { name: "Basic Salad", carbs:18, protein:6, fat:4, vitamins:10, cal:800, tier:"starter", biomes:["any"] },
    { name: "Scrap Meat", carbs:0, protein:5, fat:5, vitamins:0, cal:50, tier:"starter", biomes:["any"] },
    { name: "Charred Sausage", carbs:0, protein:10, fat:14, vitamins:0, cal:700, tier:"campfire", biomes:["any"] },
    { name: "Clam Chowder", carbs:16, protein:15, fat:3, vitamins:11, cal:800, tier:"cooked", biomes:["aquatic"] },
    { name: "Wild Stew", carbs:10, protein:2, fat:6, vitamins:12, cal:1100, tier:"cooked", biomes:["forest"] },
    { name: "Fried Vegetables", carbs:11, protein:3, fat:8, vitamins:2, cal:560, tier:"cooked", biomes:["any"] },
    { name: "Tasty Tropical Pizza", carbs:21, protein:6, fat:12, vitamins:11, cal:1200, tier:"advanced", biomes:["rainforest"] },
    { name: "Meat Pie", carbs:18, protein:4, fat:20, vitamins:2, cal:1300, tier:"baked", biomes:["any"] },
    { name: "Fireweed Shoots", carbs:3, protein:1, fat:0, vitamins:4, cal:150, tier:"gatherer", biomes:["grassland"] },
    { name: "Crimson Salad", carbs:13, protein:7, fat:8, vitamins:28, cal:1200, tier:"advanced", biomes:["any"] },
    { name: "Baked Tomato", carbs:16, protein:1, fat:5, vitamins:6, cal:700, tier:"baked", biomes:["grassland"] },
    { name: "Corn Fritters", carbs:13, protein:4, fat:22, vitamins:8, cal:500, tier:"cooked", biomes:["grassland"] },
    { name: "Baked Meat", carbs:0, protein:17, fat:13, vitamins:0, cal:700, tier:"baked", biomes:["any"] },
    { name: "Bison Chow Fun", carbs:16, protein:13, fat:20, vitamins:8, cal:1450, tier:"advanced", biomes:["grassland"] },
    { name: "Pineapple Friend Rice", carbs:20, protein:9, fat:12, vitamins:12, cal:720, tier:"cooked", biomes:["rainforest"] },
    { name: "Baked Roast", carbs:4, protein:16, fat:10, vitamins:4, cal:1000, tier:"baked", biomes:["any"] },
    { name: "Camas Bread", carbs:13, protein:5, fat:11, vitamins:7, cal:800, tier:"baked", biomes:["grassland"] },
    { name: "Elk Taco", carbs:15, protein:8, fat:22, vitamins:6, cal:700, tier:"cooked", biomes:["forest"] },
    { name: "Flaxseed Oil", carbs:0, protein:0, fat:15, vitamins:0, cal:120, tier:"starter", biomes:["grassland"] },
    { name: "Sugar", carbs:15, protein:0, fat:0, vitamins:0, cal:50, tier:"starter", biomes:["any"] },
    { name: "Papaya", carbs:2, protein:1, fat:0, vitamins:5, cal:200, tier:"gatherer", biomes:["rainforest"] },
    { name: "Infused Oil", carbs:0, protein:0, fat:12, vitamins:3, cal:120, tier:"advanced", biomes:["any"] },
    { name: "Wilted Fiddleheads", carbs:4, protein:1, fat:0, vitamins:7, cal:350, tier:"gatherer", biomes:["forest"] },
    { name: "Wild Mix", carbs:15, protein:6, fat:4, vitamins:21, cal:800, tier:"cooked", biomes:["any"] },
    { name: "Elk Wellington", carbs:10, protein:26, fat:22, vitamins:4, cal:1450, tier:"advanced", biomes:["forest"] },
    { name: "Wheat", carbs:6, protein:2, fat:0, vitamins:0, cal:150, tier:"gatherer", biomes:["grassland"] },
    { name: "Bear S U P R E M E", carbs:6, protein:22, fat:23, vitamins:9, cal:1250, tier:"advanced", biomes:["forest"] },
    { name: "Vegetable Stock", carbs:11, protein:1, fat:2, vitamins:11, cal:700, tier:"cooked", biomes:["any"] },
    { name: "Vegetable Soup", carbs:12, protein:4, fat:7, vitamins:19, cal:1200, tier:"cooked", biomes:["any"] },
    { name: "Autumn Stew", carbs:13, protein:8, fat:5, vitamins:12, cal:1200, tier:"cooked", biomes:["forest"] },
    { name: "Bean Paste", carbs:3, protein:5, fat:7, vitamins:0, cal:40, tier:"starter", biomes:["any"] },
    { name: "Bearclaw", carbs:14, protein:4, fat:21, vitamins:7, cal:850, tier:"baked", biomes:["forest"] },
    { name: "Pirozhok", carbs:14, protein:19, fat:10, vitamins:4, cal:850, tier:"advanced", biomes:["any"] },
    { name: "Bread", carbs:23, protein:6, fat:4, vitamins:2, cal:750, tier:"baked", biomes:["any"] },
    { name: "Seared Meat", carbs:4, protein:19, fat:17, vitamins:7, cal:600, tier:"cooked", biomes:["any"] },
    { name: "Prickly Pear Fruit", carbs:2, protein:1, fat:1, vitamins:4, cal:190, tier:"gatherer", biomes:["desert"] },
    { name: "Phad Thai", carbs:9, protein:11, fat:19, vitamins:5, cal:1200, tier:"advanced", biomes:["any"] },
    { name: "Camas Bulb", carbs:1, protein:2, fat:5, vitamins:0, cal:150, tier:"gatherer", biomes:["grassland"] },
    { name: "Topped Porridge", carbs:10, protein:4, fat:0, vitamins:10, cal:700, tier:"cooked", biomes:["any"] },
    { name: "Dried Meat", carbs:1, protein:14, fat:4, vitamins:0, cal:550, tier:"campfire", biomes:["any"] },
    { name: "Tomato", carbs:5, protein:1, fat:0, vitamins:2, cal:240, tier:"gatherer", biomes:["grassland"] },
    { name: "Campfire Stew", carbs:5, protein:10, fat:9, vitamins:4, cal:1200, tier:"campfire", biomes:["any"] },
    { name: "Taro Fries", carbs:10, protein:2, fat:20, vitamins:0, cal:600, tier:"cooked", biomes:["rainforest"] },
    { name: "Tallow", carbs:0, protein:0, fat:8, vitamins:0, cal:200, tier:"starter", biomes:["any"] },
    { name: "Sweet Salad", carbs:18, protein:9, fat:7, vitamins:22, cal:1200, tier:"advanced", biomes:["any"] },
    { name: "Raw Fish", carbs:0, protein:7, fat:3, vitamins:0, cal:200, tier:"gatherer", biomes:["aquatic"] },
    { name: "Sweet Deer Jerky", carbs:4, protein:22, fat:6, vitamins:3, cal:600, tier:"campfire", biomes:["forest"] },
    { name: "Beet Greens", carbs:3, protein:1, fat:0, vitamins:4, cal:100, tier:"gatherer", biomes:["grassland"] }
];