export const RAW_FOODS = [
  // ------------------------- Original items (updated with new tiers & biomes) -------------------------
  { name: "Heart Of Palm", carbs: 4, protein: 2, fat: 0, vitamins: 2, cal: 100, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Bolete Mushrooms", carbs: 2, protein: 4, fat: 1, vitamins: 1, cal: 200, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Leavened Dough", carbs: 6, protein: 18, fat: 13, vitamins: 5, cal: 10, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Charred Taro", carbs: 10, protein: 1, fat: 0, vitamins: 1, cal: 350, tier: "Campfire Cooking", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Taro Root", carbs: 6, protein: 1, fat: 0, vitamins: 1, cal: 250, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Baked Agave", carbs: 14, protein: 2, fat: 4, vitamins: 8, cal: 700, tier: "Baked Foods", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Huckleberries", carbs: 2, protein: 0, fat: 0, vitamins: 6, cal: 150, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Pupusas", carbs: 6, protein: 11, fat: 9, vitamins: 14, cal: 900, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Vegetable Medley", carbs: 8, protein: 4, fat: 7, vitamins: 17, cal: 900, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Huckleberry Fritter", carbs: 16, protein: 0, fat: 20, vitamins: 8, cal: 900, tier: "Baked Foods", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Baked Heart Of Palm", carbs: 12, protein: 6, fat: 4, vitamins: 6, cal: 700, tier: "Baked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Camas Bulb Bake", carbs: 12, protein: 7, fat: 5, vitamins: 4, cal: 700, tier: "Baked Foods", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Pineapple", carbs: 6, protein: 0, fat: 0, vitamins: 2, cal: 200, tier: "Fruit Only", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Basic Salad", carbs: 18, protein: 6, fat: 4, vitamins: 10, cal: 800, tier: "Salads Only", biomes: ["any"] },
  { name: "Scrap Meat", carbs: 0, protein: 5, fat: 5, vitamins: 0, cal: 50, tier: "Meat Only", biomes: ["any"] },
  { name: "Charred Sausage", carbs: 0, protein: 10, fat: 14, vitamins: 0, cal: 700, tier: "Campfire Cooking", biomes: ["any"] },
  { name: "Clam Chowder", carbs: 16, protein: 15, fat: 3, vitamins: 11, cal: 800, tier: "Stews", biomes: ["Ocean Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Wild Stew", carbs: 10, protein: 2, fat: 6, vitamins: 12, cal: 1100, tier: "Stews", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Fried Vegetables", carbs: 11, protein: 3, fat: 8, vitamins: 2, cal: 560, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Tasty Tropical Pizza", carbs: 21, protein: 6, fat: 12, vitamins: 11, cal: 1200, tier: "Advanced Cooking", biomes: ["Rainforest Biome", "Warm Coast Biome"] },
  { name: "Meat Pie", carbs: 18, protein: 4, fat: 20, vitamins: 2, cal: 1300, tier: "Baked Foods", biomes: ["any"] },
  { name: "Fireweed Shoots", carbs: 3, protein: 1, fat: 0, vitamins: 4, cal: 150, tier: "Gathering", biomes: ["Tundra Biome", "Boreal Forest Biome"] },
  { name: "Crimson Salad", carbs: 13, protein: 7, fat: 8, vitamins: 28, cal: 1200, tier: "Salads Only", biomes: ["any"] },
  { name: "Baked Tomato", carbs: 16, protein: 1, fat: 5, vitamins: 6, cal: 700, tier: "Baked Foods", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Corn Fritters", carbs: 13, protein: 4, fat: 22, vitamins: 8, cal: 500, tier: "Cooked Foods", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Baked Meat", carbs: 0, protein: 17, fat: 13, vitamins: 0, cal: 700, tier: "Baked Foods", biomes: ["any"] },
  { name: "Bison Chow Fun", carbs: 16, protein: 13, fat: 20, vitamins: 8, cal: 1450, tier: "Advanced Cooking", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Pineapple Friend Rice", carbs: 20, protein: 9, fat: 12, vitamins: 12, cal: 720, tier: "Cooked Foods", biomes: ["Rainforest Biome", "Warm Coast Biome"] },
  { name: "Baked Roast", carbs: 4, protein: 16, fat: 10, vitamins: 4, cal: 1000, tier: "Baked Foods", biomes: ["any"] },
  { name: "Camas Bread", carbs: 13, protein: 5, fat: 11, vitamins: 7, cal: 800, tier: "Baked Foods", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Elk Taco", carbs: 15, protein: 8, fat: 22, vitamins: 6, cal: 700, tier: "Cooked Foods", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Flaxseed Oil", carbs: 0, protein: 0, fat: 15, vitamins: 0, cal: 120, tier: "Starter", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Sugar", carbs: 15, protein: 0, fat: 0, vitamins: 0, cal: 50, tier: "Starter", biomes: ["any"] },
  { name: "Papaya", carbs: 2, protein: 1, fat: 0, vitamins: 5, cal: 200, tier: "Fruit Only", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Infused Oil", carbs: 0, protein: 0, fat: 12, vitamins: 3, cal: 120, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Wilted Fiddleheads", carbs: 4, protein: 1, fat: 0, vitamins: 7, cal: 350, tier: "Gathering", biomes: ["Cold Forest Biome", "Wetland Biome"] },
  { name: "Wild Mix", carbs: 15, protein: 6, fat: 4, vitamins: 21, cal: 800, tier: "Salads Only", biomes: ["any"] },
  { name: "Elk Wellington", carbs: 10, protein: 26, fat: 22, vitamins: 4, cal: 1450, tier: "Advanced Cooking", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Wheat", carbs: 6, protein: 2, fat: 0, vitamins: 0, cal: 150, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Bear S U P R E M E", carbs: 6, protein: 22, fat: 23, vitamins: 9, cal: 1250, tier: "Advanced Cooking", biomes: ["Boreal Forest Biome", "Cold Forest Biome"] },
  { name: "Vegetable Stock", carbs: 11, protein: 1, fat: 2, vitamins: 11, cal: 700, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Vegetable Soup", carbs: 12, protein: 4, fat: 7, vitamins: 19, cal: 1200, tier: "Stews", biomes: ["any"] },
  { name: "Autumn Stew", carbs: 13, protein: 8, fat: 5, vitamins: 12, cal: 1200, tier: "Stews", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Bean Paste", carbs: 3, protein: 5, fat: 7, vitamins: 0, cal: 40, tier: "Starter", biomes: ["any"] },
  { name: "Bearclaw", carbs: 14, protein: 4, fat: 21, vitamins: 7, cal: 850, tier: "Baked Foods", biomes: ["Boreal Forest Biome", "Cold Forest Biome"] },
  { name: "Pirozhok", carbs: 14, protein: 19, fat: 10, vitamins: 4, cal: 850, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Bread", carbs: 23, protein: 6, fat: 4, vitamins: 2, cal: 750, tier: "Baked Foods", biomes: ["any"] },
  { name: "Seared Meat", carbs: 4, protein: 19, fat: 17, vitamins: 7, cal: 600, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Prickly Pear Fruit", carbs: 2, protein: 1, fat: 1, vitamins: 4, cal: 190, tier: "Fruit Only", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Phad Thai", carbs: 9, protein: 11, fat: 19, vitamins: 5, cal: 1200, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Camas Bulb", carbs: 1, protein: 2, fat: 5, vitamins: 0, cal: 150, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Topped Porridge", carbs: 10, protein: 4, fat: 0, vitamins: 10, cal: 700, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Dried Meat", carbs: 1, protein: 14, fat: 4, vitamins: 0, cal: 550, tier: "Campfire Cooking", biomes: ["any"] },
  { name: "Tomato", carbs: 5, protein: 1, fat: 0, vitamins: 2, cal: 240, tier: "Vegetables Only", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Campfire Stew", carbs: 5, protein: 10, fat: 9, vitamins: 4, cal: 1200, tier: "Stews", biomes: ["any"] },
  { name: "Taro Fries", carbs: 10, protein: 2, fat: 20, vitamins: 0, cal: 600, tier: "Cooked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Tallow", carbs: 0, protein: 0, fat: 8, vitamins: 0, cal: 200, tier: "Starter", biomes: ["any"] },
  { name: "Sweet Salad", carbs: 18, protein: 9, fat: 7, vitamins: 22, cal: 1200, tier: "Salads Only", biomes: ["any"] },
  { name: "Raw Fish", carbs: 0, protein: 7, fat: 3, vitamins: 0, cal: 200, tier: "Raw Food", biomes: ["Ocean Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Sweet Deer Jerky", carbs: 4, protein: 22, fat: 6, vitamins: 3, cal: 600, tier: "Campfire Cooking", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Beet Greens", carbs: 3, protein: 1, fat: 0, vitamins: 4, cal: 100, tier: "Vegetables Only", biomes: ["Grassland Biome", "Wetland Biome"] },

  // ------------------------- New items from CSV (assigned tiers & biomes) -------------------------
  { name: "Spruce Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Boreal Forest Biome", "Cold Forest Biome"] },
  { name: "Cotton Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Jointfir Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Charred Agave", carbs: 5, protein: 1, fat: 3, vitamins: 3, cal: 350, tier: "Campfire Cooking", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Grass Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Maltodextrin", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 10, tier: "Starter", biomes: ["any"] },
  { name: "Ceiba Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Smooth Gut Noodle Roll", carbs: 19, protein: 15, fat: 9, vitamins: 1, cal: 1200, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Lattice Mushroom Spores", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Wetland Biome", "Rainforest Biome"] },
  { name: "Redwood Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Warm Forest Biome", "Rainforest Biome"] },
  { name: "Cornmeal", carbs: 9, protein: 3, fat: 3, vitamins: 0, cal: 60, tier: "Starter", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Campfire Salad", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Salads Only", biomes: ["any"] },
  { name: "Beet Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Wetland Biome"] },
  { name: "Acorn", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Acorn Powder", carbs: 1, protein: 5, fat: 2, vitamins: 5, cal: 40, tier: "Starter", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Kelp Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Ocean Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Corn Starch", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 10, tier: "Starter", biomes: ["any"] },
  { name: "Shark Fillet Soup", carbs: 10, protein: 15, fat: 11, vitamins: 4, cal: 1400, tier: "Stews", biomes: ["Ocean Biome", "Deep Ocean Biome", "Warm Coast Biome"] },
  { name: "Bullrush Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Wetland Biome", "Coast Biome"] },
  { name: "Sunflower Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Birch Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Cookeina Mushrooms", carbs: 2, protein: 4, fat: 1, vitamins: 1, cal: 200, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Camas Paste", carbs: 3, protein: 2, fat: 10, vitamins: 0, cal: 60, tier: "Starter", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Dwarf Willow Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Tundra Biome", "Ice Biome"] },
  { name: "Pineapple Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Fried Hearts Of Palm", carbs: 13, protein: 3, fat: 6, vitamins: 2, cal: 700, tier: "Cooked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Lupine Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Creosote Flower", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Waterweed Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Wetland Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Charred Fireweed Shoots", carbs: 5, protein: 1, fat: 0, vitamins: 6, cal: 350, tier: "Campfire Cooking", biomes: ["Tundra Biome", "Boreal Forest Biome"] },
  { name: "Charred Papaya", carbs: 3, protein: 1, fat: 0, vitamins: 8, cal: 350, tier: "Campfire Cooking", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Tulip Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Trillium Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Wetland Biome"] },
  { name: "Trillium Flower", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Wetland Biome"] },
  { name: "Transglutaminase", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 10, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Saguaro Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Cedar Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Warm Forest Biome", "Cold Forest Biome"] },
  { name: "Pastry Dough", carbs: 4, protein: 0, fat: 0, vitamins: 4, cal: 10, tier: "Starter", biomes: ["any"] },
  { name: "Tomato Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Joshua Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Taro Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Amanita Mushroom Spores", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Sunflower", carbs: 2, protein: 2, fat: 4, vitamins: 0, cal: 50, tier: "Vegetables Only", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Orchid", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Palm Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Coast Biome"] },
  { name: "Raw Bacon", carbs: 0, protein: 3, fat: 9, vitamins: 0, cal: 200, tier: "Raw Food", biomes: ["any"] },
  { name: "Pumpkin Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Worldly Donut", carbs: 15, protein: 2, fat: 17, vitamins: 2, cal: 750, tier: "Baked Foods", biomes: ["any"] },
  { name: "Stuffed Turkey", carbs: 17, protein: 24, fat: 16, vitamins: 7, cal: 1600, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Spiky Roll", carbs: 20, protein: 17, fat: 7, vitamins: 2, cal: 1300, tier: "Advanced Cooking", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Baked Corn", carbs: 12, protein: 3, fat: 2, vitamins: 11, cal: 700, tier: "Baked Foods", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Jungle Campfire Salad", carbs: 11, protein: 4, fat: 3, vitamins: 10, cal: 900, tier: "Salads Only", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Simmered Meat", carbs: 6, protein: 18, fat: 13, vitamins: 5, cal: 900, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Beet Campfire Salad", carbs: 8, protein: 4, fat: 3, vitamins: 13, cal: 900, tier: "Salads Only", biomes: ["Grassland Biome", "Wetland Biome"] },
  { name: "Sensuous Sea Pizza", carbs: 28, protein: 11, fat: 7, vitamins: 4, cal: 1200, tier: "Advanced Cooking", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Seeded Camas Roll", carbs: 20, protein: 2, fat: 13, vitamins: 16, cal: 1400, tier: "Baked Foods", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Seagrass Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Ocean Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Beet", carbs: 2, protein: 0, fat: 2, vitamins: 4, cal: 230, tier: "Vegetables Only", biomes: ["Grassland Biome", "Wetland Biome"] },
  { name: "Meaty Stew", carbs: 6, protein: 13, fat: 10, vitamins: 1, cal: 1100, tier: "Stews", biomes: ["any"] },
  { name: "Ocean Spray Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Coast Biome", "Beaches and shallow waters"] },
  { name: "Fern Spore", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Wetland Biome", "Rainforest Biome"] },
  { name: "Roast Pumpkin", carbs: 23, protein: 2, fat: 2, vitamins: 7, cal: 1400, tier: "Baked Foods", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Fried Hare Haunches", carbs: 6, protein: 15, fat: 27, vitamins: 4, cal: 750, tier: "Cooked Foods", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Saxifrage Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Tundra Biome", "Ice Biome"] },
  { name: "Fried Tomatoes", carbs: 11, protein: 3, fat: 8, vitamins: 2, cal: 700, tier: "Cooked Foods", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Tortilla", carbs: 20, protein: 10, fat: 0, vitamins: 0, cal: 350, tier: "Baked Foods", biomes: ["any"] },
  { name: "Rose Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Corn Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Dried Fish", carbs: 1, protein: 16, fat: 2, vitamins: 0, cal: 450, tier: "Campfire Cooking", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Rice Noodles", carbs: 10, protein: 0, fat: 0, vitamins: 0, cal: 200, tier: "Starter", biomes: ["any"] },
  { name: "Charred Beans", carbs: 1, protein: 8, fat: 3, vitamins: 0, cal: 350, tier: "Campfire Cooking", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Kelpy Crab Roll", carbs: 22, protein: 13, fat: 11, vitamins: 5, cal: 1350, tier: "Advanced Cooking", biomes: ["Ocean Biome", "Coast Biome", "Beaches and shallow waters"] },
  { name: "Wheat Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Rice", carbs: 7, protein: 1, fat: 0, vitamins: 0, cal: 150, tier: "Gathering", biomes: ["Wetland Biome", "Rainforest Biome"] },
  { name: "Charred Beet", carbs: 3, protein: 0, fat: 3, vitamins: 6, cal: 350, tier: "Campfire Cooking", biomes: ["Grassland Biome", "Wetland Biome"] },
  { name: "Charred Cactus Fruit", carbs: 4, protein: 0, fat: 2, vitamins: 6, cal: 200, tier: "Campfire Cooking", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Agave Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Big Bluestem Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Pumpkin", carbs: 5, protein: 1, fat: 0, vitamins: 2, cal: 340, tier: "Vegetables Only", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Agave Leaves", carbs: 2, protein: 1, fat: 1, vitamins: 4, cal: 200, tier: "Vegetables Only", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Raw Roast", carbs: 0, protein: 6, fat: 5, vitamins: 0, cal: 600, tier: "Raw Food", biomes: ["any"] },
  { name: "Milk", carbs: 3, protein: 10, fat: 7, vitamins: 0, cal: 120, tier: "Starter", biomes: ["any"] },
  { name: "Barrel Cactus Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Flax Flower", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Fish N Chips", carbs: 20, protein: 10, fat: 20, vitamins: 0, cal: 1000, tier: "Cooked Foods", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Fir Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Raw Meat", carbs: 0, protein: 4, fat: 8, vitamins: 0, cal: 250, tier: "Raw Food", biomes: ["any"] },
  { name: "Sugarcane", carbs: 0, protein: 0, fat: 1, vitamins: 0, cal: 1, tier: "Starter", biomes: ["Warm Forest Biome", "Rainforest Biome"] },
  { name: "Agouti Enchiladas", carbs: 20, protein: 8, fat: 27, vitamins: 3, cal: 800, tier: "Advanced Cooking", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Prime Cut", carbs: 0, protein: 9, fat: 4, vitamins: 0, cal: 600, tier: "Meat Only", biomes: ["any"] },
  { name: "Prickly Pear Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Baked Taro", carbs: 8, protein: 6, fat: 2, vitamins: 12, cal: 700, tier: "Baked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Prepared Meat", carbs: 0, protein: 4, fat: 6, vitamins: 0, cal: 600, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Filmy Fern Spore", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Wetland Biome"] },
  { name: "Campfire Roast", carbs: 0, protein: 16, fat: 12, vitamins: 0, cal: 1000, tier: "Campfire Cooking", biomes: ["any"] },
  { name: "Boiled Sausage", carbs: 0, protein: 27, fat: 22, vitamins: 0, cal: 600, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Papaya Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Field Campfire Stew", carbs: 14, protein: 4, fat: 8, vitamins: 4, cal: 1100, tier: "Stews", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Sun Butter", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Starter", biomes: ["any"] },
  { name: "Orchid Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Bunchgrass Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Mochi", carbs: 25, protein: 0, fat: 0, vitamins: 5, cal: 750, tier: "Baked Foods", biomes: ["any"] },
  { name: "Root Campfire Stew", carbs: 8, protein: 5, fat: 12, vitamins: 5, cal: 1100, tier: "Stews", biomes: ["any"] },
  { name: "Meat Stock", carbs: 3, protein: 8, fat: 9, vitamins: 0, cal: 600, tier: "Starter", biomes: ["any"] },
  { name: "Macarons", carbs: 20, protein: 7, fat: 14, vitamins: 16, cal: 1000, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Rice Flour", carbs: 15, protein: 0, fat: 0, vitamins: 0, cal: 50, tier: "Starter", biomes: ["any"] },
  { name: "Fruit Salad", carbs: 12, protein: 4, fat: 3, vitamins: 19, cal: 900, tier: "Salads Only", biomes: ["any"] },
  { name: "Flour", carbs: 15, protein: 0, fat: 0, vitamins: 0, cal: 50, tier: "Starter", biomes: ["any"] },
  { name: "Liquid Nitrogen", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 10, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "King Fern Spore", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Wetland Biome"] },
  { name: "Jungle Campfire Stew", carbs: 8, protein: 8, fat: 11, vitamins: 3, cal: 1100, tier: "Stews", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Fried Taro", carbs: 14, protein: 1, fat: 8, vitamins: 1, cal: 700, tier: "Cooked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Simple Syrup", carbs: 12, protein: 0, fat: 3, vitamins: 0, cal: 400, tier: "Starter", biomes: ["any"] },
  { name: "Boiled Rice", carbs: 13, protein: 2, fat: 0, vitamins: 0, cal: 210, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Huckleberry Extract", carbs: 0, protein: 0, fat: 0, vitamins: 15, cal: 60, tier: "Starter", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Bannock", carbs: 15, protein: 3, fat: 6, vitamins: 0, cal: 700, tier: "Baked Foods", biomes: ["any"] },
  { name: "Fireweed Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Tundra Biome", "Boreal Forest Biome"] },
  { name: "Fried Fiddleheads", carbs: 11, protein: 3, fat: 6, vitamins: 4, cal: 700, tier: "Cooked Foods", biomes: ["Cold Forest Biome", "Wetland Biome"] },
  { name: "Fried Camas", carbs: 9, protein: 3, fat: 10, vitamins: 2, cal: 700, tier: "Cooked Foods", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Fruit Tart", carbs: 22, protein: 3, fat: 9, vitamins: 14, cal: 800, tier: "Baked Foods", biomes: ["any"] },
  { name: "Hydrocolloids", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 10, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Heliconia Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Hosomaki", carbs: 21, protein: 19, fat: 5, vitamins: 8, cal: 700, tier: "Advanced Cooking", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Crimini Mushroom Spores", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Grassland Biome"] },
  { name: "Flax Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Yeast", carbs: 0, protein: 8, fat: 0, vitamins: 7, cal: 60, tier: "Starter", biomes: ["any"] },
  { name: "Huckleberry Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Cereal Germ", carbs: 5, protein: 0, fat: 7, vitamins: 3, cal: 20, tier: "Starter", biomes: ["any"] },
  { name: "Bean Sprout", carbs: 2, protein: 1, fat: 0, vitamins: 5, cal: 100, tier: "Vegetables Only", biomes: ["any"] },
  { name: "Charred Camas Bulb", carbs: 2, protein: 3, fat: 6, vitamins: 1, cal: 350, tier: "Campfire Cooking", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Loaded Taro Fries", carbs: 14, protein: 6, fat: 18, vitamins: 0, cal: 1200, tier: "Cooked Foods", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Beans", carbs: 1, protein: 4, fat: 3, vitamins: 0, cal: 150, tier: "Vegetables Only", biomes: ["any"] },
  { name: "Fruit Muffin", carbs: 10, protein: 5, fat: 4, vitamins: 16, cal: 800, tier: "Baked Foods", biomes: ["any"] },
  { name: "Huckleberry Pie", carbs: 13, protein: 5, fat: 10, vitamins: 16, cal: 1300, tier: "Baked Foods", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Amanita Mushrooms", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: -200, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Hearty Hometown Pizza", carbs: 28, protein: 7, fat: 11, vitamins: 3, cal: 1200, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "White Bursage Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Bolete Mushroom Spores", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Giant Cactus Fruit", carbs: 2, protein: 0, fat: 2, vitamins: 4, cal: 100, tier: "Fruit Only", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Fiddleheads", carbs: 2, protein: 1, fat: 0, vitamins: 5, cal: 150, tier: "Vegetables Only", biomes: ["Wetland Biome", "Cold Forest Biome"] },
  { name: "Charred Corn", carbs: 7, protein: 1, fat: 0, vitamins: 4, cal: 350, tier: "Campfire Cooking", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Crimini Mushrooms", carbs: 2, protein: 4, fat: 1, vitamins: 1, cal: 200, tier: "Gathering", biomes: ["Cold Forest Biome", "Grassland Biome"] },
  { name: "Oil", carbs: 0, protein: 0, fat: 15, vitamins: 0, cal: 120, tier: "Starter", biomes: ["any"] },
  { name: "Fantastic Forest Pizza", carbs: 23, protein: 4, fat: 10, vitamins: 17, cal: 1250, tier: "Advanced Cooking", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Ecoylent", carbs: 500, protein: 500, fat: 500, vitamins: 500, cal: 1500, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Flatbread", carbs: 17, protein: 8, fat: 3, vitamins: 2, cal: 500, tier: "Baked Foods", biomes: ["any"] },
  { name: "Charred Fish", carbs: 0, protein: 11, fat: 4, vitamins: 0, cal: 400, tier: "Campfire Cooking", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Root Campfire Salad", carbs: 8, protein: 5, fat: 4, vitamins: 11, cal: 950, tier: "Salads Only", biomes: ["any"] },
  { name: "Poke Bowl", carbs: 21, protein: 10, fat: 11, vitamins: 7, cal: 1100, tier: "Advanced Cooking", biomes: ["Ocean Biome", "Coast Biome"] },
  { name: "Crispy Bacon", carbs: 0, protein: 18, fat: 26, vitamins: 0, cal: 800, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Charred Heart Of Palm", carbs: 6, protein: 3, fat: 1, vitamins: 2, cal: 210, tier: "Campfire Cooking", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Corn", carbs: 4, protein: 1, fat: 0, vitamins: 3, cal: 230, tier: "Vegetables Only", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Creosote Bush Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Desert Biome", "High Desert Biome"] },
  { name: "Millionaires Salad", carbs: 18, protein: 6, fat: 6, vitamins: 26, cal: 1000, tier: "Salads Only", biomes: ["any"] },
  { name: "Cookeina Mushroom Spores", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Banh Xeo", carbs: 26, protein: 17, fat: 10, vitamins: 4, cal: 1550, tier: "Advanced Cooking", biomes: ["any"] },
  { name: "Charred Pineapple", carbs: 8, protein: 1, fat: 0, vitamins: 3, cal: 350, tier: "Campfire Cooking", biomes: ["Rainforest Biome", "Warm Forest Biome"] },
  { name: "Arctic Willow Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Tundra Biome", "Ice Biome"] },
  { name: "Charred Mushrooms", carbs: 3, protein: 6, fat: 2, vitamins: 1, cal: 350, tier: "Campfire Cooking", biomes: ["Cold Forest Biome", "Boreal Forest Biome"] },
  { name: "Charred Meat", carbs: 0, protein: 5, fat: 10, vitamins: 0, cal: 400, tier: "Campfire Cooking", biomes: ["any"] },
  { name: "Raw Sausage", carbs: 0, protein: 4, fat: 8, vitamins: 0, cal: 500, tier: "Raw Food", biomes: ["any"] },
  { name: "Fern Campfire Salad", carbs: 9, protein: 5, fat: 1, vitamins: 13, cal: 900, tier: "Salads Only", biomes: ["Wetland Biome", "Rainforest Biome"] },
  { name: "Daisy Seed", carbs: 0, protein: 0, fat: 0, vitamins: 0, cal: 0, tier: "Gathering", biomes: ["Grassland Biome", "Steppe Biome"] },
  { name: "Boiled Grains", carbs: 9, protein: 2, fat: 0, vitamins: 1, cal: 350, tier: "Cooked Foods", biomes: ["any"] },
  { name: "Charred Tomato", carbs: 7, protein: 1, fat: 0, vitamins: 4, cal: 350, tier: "Campfire Cooking", biomes: ["Grassland Biome", "Warm Forest Biome"] },
  { name: "Baked Beet", carbs: 10, protein: 1, fat: 2, vitamins: 15, cal: 700, tier: "Baked Foods", biomes: ["Grassland Biome", "Wetland Biome"] },
];
